docs/components/date-picker.md
=> date-picker 文档补充 demo

demos/grid/index.js, demos/tooltip/index.html, src/common/utils/position/index.js, src/components/grid/GridCtrl.js, src/components/grid/GridHelper.js, src/components/grid/tpls/checkbox-header.tpl.html, src/components/tooltip/Tooltip.js, src/components/tooltip/TooltipCtrl.js, src/components/tooltip/TooltipDirectives.js, src/components/tooltip/index.js
1.删除表格半选状态
2.tooltip节点改为动态生成&销毁 
3.tooltip支持将节点append到body里
=> tooltip improvement

demos/dropdown/index.html, src/components/dropdown/dropdown-select/DropdownSelectCtrl.js, src/components/dropdown/dropdown-select/_dropdown-select.scss, src/components/dropdown/dropdown-select/dropdown-select.tpl.html, src/components/dropdown/dropdown-select/index.js, src/components/styles/_input.scss
=> dropdown-select 优化

src/components/grid/GridHelper.js, src/components/grid/_grid.scss, src/components/grid/grid.tpl.html, src/components/pagination/PaginationCtrl.js, src/components/pagination/index.js, src/components/pagination/pagination.tpl.html
1. [bugfix]将翻页信息初始化职责划分给pagination组件,解决因为初始化问题导致的bug
2. [feat]当总页数只有一页时,禁止用户输入
=> 翻页功能代码调整&bug修复

src/components/styles/_base.scss, src/components/styles/_layout.scss
=> 添加Layout样式引用

src/components/modal/_modal.scss
bugfix(modal):modal-body区position设置为relative,这样可以避免modal内部定位出现异常的问题
=> bugfix(modal):modal-body区position设置为relative

demos/date-picker/index.html, src/components/calendar/CalendarCtrl.js, src/components/calendar/calendar.tpl.html
dateOnly 设置下，点击「现在」会无法选择的问题
日历输入时间的响应时机从 blur 改为 keyup
=> Datepicker

docs/components/layout.md
=> Layout 说明文档更新

docs/components/menus.md
=> menus组件使用文档更新

demos/menus/menus.html, src/components/menus/_shop-selector.scss
修复COMPONENTS-66，鼠标略过头像时整个区域上需要显示手型
=> 修复COMPONENTS-66

src/components/styles/_layout.scss
删除ccmsc-main-container容器的min-height样式
=> style(layout): 1. 删除min-height

src/components/menus/MenusCtrl.js, src/components/menus/ShopSelectsCtrl.js
=> perf(menus): 1. 删除组件中多余代码    2. 修改店铺选择器关闭方式

src/components/menus/MenusCtrl.js, src/components/menus/_menu.scss, src/components/menus/menus.tpl.html
=> pref(menus): 修复无配置shop-source信息,则不展示店铺相关展示

src/components/modal/ModalService.js, src/components/modal/modal.tpl.html
feat(modal): 组件可以通过配置 uid 修改默认的 modal css 属性
=> feat(modal): 组件可以通过配置 uid 修改默认的 modal css 属性

docs/_data/nav.yml, docs/components/radio-button.md
docs(radio-button): create radio-button component doc file
=> docs(radio-button): create radio-button component doc file

demos/checkbox/index.html, docs/_data/nav.yml, docs/components/checkbox.md
docs(checkbox): create checkbox component doc file
=> docs(checkbox): create checkbox component doc file

.github/PULL_REQUEST_TEMPLATE.md
=> feature(pr-template): 新增 pull request template

src/components/menus/_menu.scss
=> fix(menus):menus overflow 时留白问题

src/common/utils/style-helper/index.js
1. 容器display为none时,获取不到tips节点宽度问题
=> fix(tips): 容器display为none时,获取不到tips节点宽度问题

demos/radio-button/index.js, src/components/radio/RadioCtrl.js
fix ng-model will be set undefined when ng-value | value equals 0
=> fix(radio-button): fix ng-model will be set undefined when ng-value equals 0

src/components/checkbox/__test__/test-CheckboxCtrl.js
test(cc-checkbox): add test of cc-checkbox
=> test(cc-checkbox): add test of cc-checkbox

src/components/radio/__test__/test-RadioCtrl.js
test(cc-radio): add test of cc-radio
=> test(cc-radio): add test of cc-radio

src/components/date-picker/DatePickerCtrl.js
=> fix(date-picker): COMPONENTS-68 - 日期组件选择日期与实际不符

docs/components/tabset.md
=> docs(tabset): 完善tabset组件文档

docs/_layouts/docs.html, docs/_sass/_content.scss, docs/components/checkbox.md, docs/components/date-picker.md, docs/components/dropdown.md, docs/components/form.md, docs/components/grid.md, docs/components/iconfont.md, docs/components/layout.md, docs/components/loading.md, docs/components/menus.md, docs/components/modal.md, docs/components/pagination.md, docs/components/radio-button.md, docs/components/tabset.md
=> feat(docs): 组件文档新增维护者

demos/tips/index.js, src/common/bases/Popup.js, src/common/utils/dom-event/index.js, src/components/modal/Modal.js, src/components/tips/Tips.js, src/components/tips/TipsService.js
see jira.yunat.com/browse/COMPONENTS-89
=> fix(tips):修复tips跟hashchange事件配合时不能正确自动销毁的bug

docs/_data/nav.yml, docs/components/switch.md
docs(cc-switch): create cc-switch component doc file
=> docs(cc-switch): create cc-switch component doc file

src/components/tips/TipsCtrl.js
=> fix(tips): 1. 修复计算内容宽度问题

demos/date-picker/index.html, src/components/calendar/CalendarCtrl.js, src/components/date-picker/DatePickerCtrl.js
可以通过代码设置 dateRange.start = null; dateRange.end = null;
=> COMPONENTS-107 日期选择器需要提供重置接口

src/components/switch/_switch.scss, src/components/switch/switch.tpl.html
=> fix(switch): 添加 disabled switch cursor的样式为 not-allowed 

demos/menus/app.js, docs/components/menus.md, package.json, src/components/menus/MenuService.js, src/components/menus/MenusCtrl.js, src/components/menus/MenusNodeCtrl.js, src/components/menus/ShopSelectsCtrl.js, src/components/menus/index.js, src/components/menus/menus.tpl.html, src/components/menus/shop-selects.tpl.html
=> refactor(menus): 修改店铺选择器监听方式

demos/menus/app.js, demos/menus/menus.html, docs/components/menus.md, package.json, src/components/menus/MenuService.js, src/components/menus/MenusCtrl.js, src/components/menus/MenusNodeCtrl.js, src/components/menus/ShopSelectsCtrl.js, src/components/menus/index.js, src/components/menus/menus-node.tpl.html, src/components/menus/menus.tpl.html, src/components/menus/shop-selects.tpl.html
=> refactor(menus): 添加cc前缀

demos/menus/app.js, demos/menus/menus.html, docs/components/menus.md, package.json, src/components/menus/MenuService.js, src/components/menus/MenusCtrl.js, src/components/menus/MenusNodeCtrl.js, src/components/menus/ShopSelectsCtrl.js, src/components/menus/index.js, src/components/menus/menus-node.tpl.html, src/components/menus/menus.tpl.html, src/components/menus/shop-selects.tpl.html
Reverts ShuyunFF2E/ccms-components#143
=> Revert "refactor(menus): 添加cc前缀"

src/components/form/index.js, src/components/tooltip/index.js
未新建作用域组件 controllerAs 以 $$ 为前缀
=> fix(form&tooltip):修复属性形指令可能出现的controllerAs别名跟当前组件控制器冲突的bug

demos/dropdown/select.html, src/components/dropdown/dropdown-select/DropdownSelectCtrl.js
=> fix(dropdown):当手动修改model值时, 下拉框 focus 位置不对

src/components/menus/menus.tpl.html
=> fix(menus): 获取店铺失败修复

server.js, src/components/customer-profile-board/CustomerAttributeSetting.js, src/components/customer-profile-board/CustomerProfileBoardCtrl.js, src/components/customer-profile-board/CustomerProfileBoardService.js, src/components/customer-profile-board/__test__/test-CustomerProfileBoardCtrl.js, src/components/customer-profile-board/__test__/test-CustomerProfileBoardService.js, src/components/customer-profile-board/__test__/test-queryStringSchema.js, src/components/customer-profile-board/customer-defined-attribute-editor/CustomerDefinedAttributeEditorCtrl.js, src/components/customer-profile-board/customer-defined-attribute-editor/__test__/test-CustomerDefinedAttributeEditorCtrl.js, src/components/customer-profile-board/customer-defined-attribute-editor/attribute-data-editor/__test__/test-AttributeDateEditorCtrl.js, src/components/customer-profile-board/customer-profile-header/CustomerProfileHeaderCtrl.js, src/components/customer-profile-board/customer-profile-header/index.js, src/components/customer-profile-board/customer-profile-list-mode/CustomerProfileListModeCtrl.js, src/components/customer-profile-board/customer-profile-list-mode/__test__/test-CustomerProfileListModeCtrl.js, src/components/customer-profile-board/customer-profile-list-mode/customer-attribute-editor/__test__/test-CustomerAttributeEditorCtrl.js, src/components/customer-profile-board/customer-profile-list-mode/customer-attribute-editor/customer-attribute-editor.tpl.html, src/components/customer-profile-board/customer-profile-view-mode/__test__/test-CustomerProfileViewModeCtrl.js, src/components/customer-profile-board/customer-profile-view-mode/customer-attribute-note/__test__/test-CustomerAttributeNoteCtrl.js, src/components/customer-profile-board/queryStringSchema.js, test/karma.base.conf.js, test/test.index.js
=> test(customer-profile-board): add UT

src/components/tips/TipsCtrl.js
=> fix(tips): 修改遗漏问题

demos/form/index.html, package.json, src/components/form/index.js
chore(package.json): 加入prepush test hook
=> fix(validator): 修复validator 升级提示不正确的问题

src/components/menus/ShopSelectsCtrl.js
=> feat(menus): 添加plat 下没有shop 则返回 undefined

demos/grid/index.html, demos/grid/index.js, src/components/nice-scroll/index.js
=> fix(nice-scroll):nicescroll覆盖的区域需要在深层次的子节点发生变化时重计算位置

src/components/customer-profile-board/CustomerAttributeSetting.js, src/components/customer-profile-board/CustomerProfileBoardCtrl.js, src/components/customer-profile-board/CustomerProfileBoardService.js, src/components/customer-profile-board/__tests__/test-queryStringSchema.js, src/components/customer-profile-board/customer-defined-attribute-editor/customer-defined-attribute-editor.tpl.html, src/components/customer-profile-board/customer-profile-header/customer-profile-header.tpl.html, src/components/customer-profile-board/customer-profile-list-mode/customer-attribute-editor/customer-attribute-editor.tpl.html, src/components/customer-profile-board/queryStringSchema.js
Enable tag schema.
Enable display customer defined properties.
=> feat(customer-profile-board): Enable tag & customer defined properties.

src/components/customer-profile-board/CustomerAttributeSetting.js
=> fix(customer-profile-board): 【列表模式】基本信息-客户的姓名为空，应显示“-”

demos/tabset/index.html, docs/components/tabset.md, src/components/tabset/_tabset.scss, src/components/tabset/index.js
=> chore(tabset): 移除组件的兼容代码

src/components/menus/index.js
=> Chore/menus: 删除兼容代码

server.js, src/components/customer-profile-board/CustomerAttributeSetting.js, src/components/customer-profile-board/CustomerProfileBoardService.js, src/components/customer-profile-board/__tests__/test-CustomerProfileBoardService.js, src/components/customer-profile-board/customer-profile-header/_customer-profile-header.scss, src/components/customer-profile-board/customer-profile-header/customer-profile-header.tpl.html
=> fix(customer-profile-board): Add business logic.

demos/customer-profile-board/index.js, src/components/customer-profile-board/CustomerAttributeSetting.js, src/components/customer-profile-board/CustomerProfileBoardService.js, src/components/customer-profile-board/__tests__/test-CustomerProfileBoardService.js, src/components/customer-profile-board/__tests__/test-queryStringSchema.js, src/components/customer-profile-board/customer-defined-attribute-editor/_customer-defined-attribute-editor.scss, src/components/customer-profile-board/customer-defined-attribute-editor/customer-defined-attribute-editor.tpl.html, src/components/customer-profile-board/customer-profile-list-mode/customer-attribute-editor/CustomerAttributeEditorCtrl.js, src/components/customer-profile-board/customer-profile-list-mode/customer-attribute-editor/__tests__/test-CustomerAttributeEditorCtrl.js, src/components/customer-profile-board/customer-profile-list-mode/customer-attribute-editor/_customer-attribute-editor.scss, src/components/customer-profile-board/customer-profile-list-mode/customer-attribute-editor/customer-attribute-editor.tpl.html, src/components/customer-profile-board/queryStringSchema.js
=> Fix(customer profile board): Fix request graphql backend bug.

demos/customer-profile-board/index.js, package.json, server.js, src/components/customer-profile-board/CustomerAttributeSetting.js, src/components/customer-profile-board/CustomerProfileBoardService.js, src/components/customer-profile-board/__tests__/test-CustomerProfileBoardService.js, src/components/customer-profile-board/__tests__/test-queryStringSchema.js, src/components/customer-profile-board/customer-defined-attribute-editor/CustomerDefinedAttributeEditorCtrl.js, src/components/customer-profile-board/customer-defined-attribute-editor/__tests__/test-CustomerDefinedAttributeEditorCtrl.js, src/components/customer-profile-board/customer-profile-list-mode/customer-attribute-editor/CustomerAttributeEditorCtrl.js, src/components/customer-profile-board/customer-profile-list-mode/customer-attribute-editor/customer-attribute-editor.tpl.html, src/components/customer-profile-board/queryStringSchema.js
=> fix(customer profile board): Attribute setting change

src/components/modal/_modal.scss
=> style(modal): 修改modal样式选择器层级关系，避免使用的时候给配置的body模板造成影响

demos/tooltip/index.html, src/components/tooltip/Tooltip.js, src/components/tooltip/TooltipCtrl.js, src/components/tooltip/index.js
=> fix(tooltip): 修复当tooltip内容为compilable 的html element 时会出现内容重复添加的问题

package.json, server.js
Revert custom local setting change.
=> Fix(server.js): Revert custom local setting change.

src/components/customer-profile-board/CustomerProfileBoardService.js, src/components/customer-profile-board/customer-profile-list-mode/customer-attribute-editor/CustomerAttributeEditorCtrl.js, src/components/customer-profile-board/customer-profile-list-mode/customer-attribute-editor/__tests__/test-CustomerAttributeEditorCtrl.js, src/components/customer-profile-board/customer-profile-list-mode/customer-attribute-editor/customer-attribute-editor.tpl.html
Add some code to fix backend leak.
=> fix(customer-profile-board): Add some code to fix backend leak.

demos/menus/app.js, src/components/menus/MenusNodeCtrl.js
=> fix(menus): 跳转问题

package.json, src/components/nice-scroll/index.js, webpack-build.config.js, webpack-common-loaders.js
=> fix(nice-scroll): 修复 windows 下 firefox 渲染能力不足，导致 dom 的异步回调会发生无效触发的情况

src/components/menus/MenusNodeCtrl.js, src/components/menus/_menu.scss
=> fix(menus):默认进入菜单时报错问题

docs/components/grid.md, src/components/grid/GridHelper.js
Revert "fix(grid): 修复 grid 合并自定义配置时的 bug (#254)"， @kuitos
=> fix(grid-recursion-stack-exceeded): 撤销引起 grid 调用栈溢出的提交

README.md, package.json, src/index.js, webpack-common-loaders.js
使用 `angular.module('ccms.components').version` 查看 ccms-components 版本。
=> feat(ccms-components-version): ccms-components 增加查看版本功能

demos/grid/external-data-grid.html, demos/grid/external-data-grid.js, src/components/grid/GridCtrl.js
1. 修复集成翻页的 grid 组件在使用 externalData 翻页时数据没有同步到 grid 配置上的 bug
2. 增加 externalData grid 的 demo
=> fix(grid): 修复集成翻页的 grid 组件在使用 externalData 翻页时数据没有同步到 grid 配置上的 bug

src/components/sms-editor/SMSEditorCtrl.js
=> fix(sms-editor): 修复短信编辑器粘贴处理

src/components/area-selector/AreaSelectorCtrl.js
=> fix(area-selector): modify the comments for area-selector

src/components/customer-profile-board/CustomerProfileBoardCtrl.js, src/components/customer-profile-board/__tests__/test-CustomerProfileBoardCtrl.js, src/components/customer-profile-board/_customer-profile-board.scss, src/components/customer-profile-board/customer-profile-board.tpl.html, src/components/customer-profile-board/customer-profile-list-mode/customer-attribute-editor/CustomerAttributeEditorCtrl.js
=> Feat(customer-profile-board): Add loading & error page.

src/components/customer-profile-board/customer-profile-list-mode/customer-attribute-editor/_customer-attribute-editor.scss
Fix last attribute block can not display whole page.
=> fix(customer-profile-board): 修复全视图会员互动点击没有被选中的问题

.gitignore, src/components/menus/_menu.scss, src/components/menus/menus.tpl.html
=> fix(ccMenus): 修复收起侧边栏时图标切换店铺模式禁用功能不生效bug

package.json
当前测试已经用不到 phantomjs， 所以从 package.json 将 phantomjs 删除
=> fix(package.json): 删除 phantomjs

.gitignore, demos/components/grid/index.html, demos/components/grid/index.js, src/components/grid/grid.tpl.html
=> fix(grid):报错提示和空数据提示重合

demos/components/date-picker/index.html, src/components/date-picker/DatePicker.js, src/components/date-picker/DatePickerCtrl.js
当直接为日期组件赋值时，如果该值不在范围内，出现 error 信息，当再次赋予正确值，错误信息未消失
=> fix(datepicker):错误信息无法关闭

demos/components/sms-editor/index.js, src/components/sms-editor/SMSEditorCtrl.js, src/components/sms-editor/sms-editor.tpl.html, src/components/sms-preview/SMSPreview.js, src/components/sms-preview/sms-preview.tpl.html
1. 关键字支持 prefix 和 suffix
2. 由于某些特殊原因，添加 trimContent 参数（请大家不要使用该参数，待后期产品统一定义该行为）
=> feat(sms-editor):为关键字添加前后缀

demos/components/select/index.html, package.json, src/components/dropdown/dropdown-select/DropdownSelectCtrl.js, src/components/dropdown/dropdown-select/_dropdown-select.scss, src/components/dropdown/dropdown-select/dropdown-select.tpl.html
**feat**(dropdown-select):  配置项中添加了icon，支持选项左侧显示icon
=> dropdown-select增加icon配置项

demos/components/grid/index.js, src/components/grid/_grid.scss
=> fix(grid):hidden columns dropdown style issue when scrollbar shows

demos/components/grid/index.js, demos/components/modal/modal-footer.tpl.html, demos/components/radio-button/index.js, demos/components/toggle/index.html, src/components/grid/_grid.scss, src/components/grid/grid.tpl.html, src/components/grid/tpls/error.tpl.html
=> fix(all):UX demo check

demos/components/modal/index.js, demos/components/modal/modal-header.tpl.html, src/components/modal/ModalService.js
=> feat(modal): 支持自定义 header

demos/components/select/index.html, package.json
=> fix(package.json):keep ccms-icons latest when install

src/components/dropdown/dropdown-multiselect/DropdownMultiselectCtrl.js, src/components/dropdown/dropdown-select/DropdownSelectCtrl.js
dropdown组件的search功能对大小写不敏感，现对于此点功能修复。
=> fix(dropdown):  bugfix search text ignore case

package.json
校验 package.json
http://package-json-validator.com/
=> fix(package.json):package.json not support latest version

demos/components/tooltip/index.html, src/components/icon/index.scss
=> fix(cc-icon): Firefox 中 cc-icon tooltip 偶尔会出现不能消失或闪烁不能显示的情况 

demos/components/sms-editor/index.js, src/components/sms-preview/SMSPreview.js, src/components/sms-preview/sms-preview.tpl.html
=> feat(sms-preview): 支持自定义短信规则提示信息 

demos/components/sms-editor/index.js, package.json, src/components/sms-editor/SMSEditorCtrl.js, src/components/sms-editor/_sms-editor.scss, src/components/sms-editor/sms-editor.tpl.html
配置shortLinkTip参数，短信编辑器中出现“c.tb.cn”、“vcrm.me”、“t.cn”判断是手动插入的短链，出现tips.
=> Feature/sms-edit : add tips when appear shortlink

src/components/sms-editor/SMSEditorCtrl.js, src/components/sms-editor/_sms-editor.scss, src/components/sms-editor/sms-editor.tpl.html
=> fix(sms-editor): change tips position when appear

package-lock.json, test/karma.base.conf.js, test/karma.cover.conf.js, test/karma.unit.conf.js
=> fix(karma):update karam config for chromeheadless

package.json
=> fix(package.json): update jquery to 3.0.0 for security

package-lock.json
=> fix(package.json): update package-lock.json

demos/components/date-picker/index.html, package-lock.json, package.json, src/components/calendar/Calendar.js, src/components/calendar/CalendarCtrl.js, src/components/calendar/_calendar.scss, src/components/calendar/calendar.tpl.html, src/components/date-picker/DatePicker.js, src/components/date-picker/date-picker.tpl.html, src/components/date-range/DateRange.js, src/components/date-range/date-range.tpl.html
=> feat(calendar): calendar support simple festival tips

demos/components/select/index.html, src/components/dropdown/dropdown-select/DropdownSelectCtrl.js, src/components/dropdown/dropdown-select/__tests__/test-cc-dropdown-select.js
=>  fix(select):on-select-change support itemIndex and item

demos/components/date-picker/index.html, src/components/date-picker/DatePicker.js, src/components/date-picker/DatePickerCtrl.js
=> fix(date-picker):date picker validation issue

demos/components/date-picker/index.html, src/components/date-picker/DatePickerCtrl.js
=> fix(date-picker):compare date issue

demos/components/grid/index.html, demos/components/grid/index.js, package-lock.json, package.json, src/components/grid/GridCtrl.js, src/components/grid/index.js
=> feat(grid): on before refresh

src/components/form/ValidatorCtrl.js
=> bugfix(form): validator 销毁时清除对应 controller

demos/components/select/index.html, package-lock.json, package.json, src/components/dropdown/dropdown-multiselect/DropdownMultiselectCtrl.js, src/components/dropdown/dropdown-multiselect/dropdown-multiselect.tpl.html, src/components/dropdown/dropdown-multiselect/index.js
=> feat(dropdown-selector): 增加全选功能

demos/components/select/index.html, src/components/dropdown/dropdown-multiselect/DropdownMultiselectCtrl.js, src/components/dropdown/dropdown-multiselect/index.js
=> fix(dropdown-select): 当异步获取 dataList 数据时, 初始化全选状态出错

src/components/goods-selector/tpls/customer-row-cell.tpl.html, src/components/goods-selector/tpls/customer-sku-row-cell.tpl.html
=> fix(goods-selector):下架商品的库存量“—件”改成“--件”

demos/components/select/index.html, src/components/dropdown/dropdown-select/DropdownSelectCtrl.js
=> fix(dropdown-select): 修复异步数据赋值 issue

src/components/dropdown/dropdown-multiselect/dropdown-multiselect.tpl.html, src/components/dropdown/dropdown-select/dropdown-select.tpl.html
=> fix(dropdown): use ngBindHtml

demos/components/sms-editor/index.html, demos/components/sms-editor/index.js, src/components/sms-editor/SMSEditorCtrl.js
=> feat(sms-editor):expose sms-editor api for users

src/components/sms-preview/SMSPreview.js
=> fix(sms-preview):export some vars

src/components/dropdown/dropdown-select/DropdownSelectCtrl.js
=> fix(dropdownSelect): 下拉框清空没有触发 change 事件

demos/components/sms-editor/index.js, package-lock.json, package.json, src/components/sms-editor/SMSEditorCtrl.js, src/components/sms-preview/SMSPreview.js
=>  fix(sms): support keyword prefix and suffix

demos/components/sms-editor/index.js, src/common/bases/common.js, src/components/sms-editor/SMSEditorCtrl.js, src/components/sms-preview/SMSPreview.js
=> fix(sms): 修复短信回显问题

demos/components/date-picker/index.html, src/common/bases/constant.js, src/components/calendar/Calendar.js, src/components/calendar/CalendarCtrl.js, src/components/calendar/calendar.tpl.html, src/components/date-picker/DatePicker.js, src/components/date-picker/DatePickerCtrl.js, src/components/date-picker/date-picker.tpl.html
=> feat(date-picker):support display format

demos/components/select/index.html, src/components/dropdown/dropdown-multiselect/DropdownMultiselectCtrl.js, src/components/dropdown/dropdown-multiselect/_dropdown-multiselect.scss, src/components/dropdown/dropdown-multiselect/dropdown-multiselect.tpl.html, src/components/dropdown/dropdown-multiselect/index.js
=> fix(cc-multi-dropdown):disabled function

demos/components/sms-editor/index.js, src/components/sms-editor/SMSEditorCtrl.js
=> fix(sms-editor):keyword length issue

demos/components/sms-editor/index.js, src/components/sms-editor/_sms-editor.scss
=> fix(sms-editor):set font-family

src/components/shop-selector/Constant.js, src/components/shop-selector/ShopSelectorCtrl.js, src/components/shop-selector/service.js
=> fix(shop-selector): 地区接口的域名由用户配置

demos/components/sms-editor/index.js, src/components/sms-editor/SMSEditorCtrl.js
=> fix(sms-editor): is support image

src/components/date-picker/DatePickerCtrl.js, src/components/date-picker/date-picker.tpl.html, src/components/instant-search/_instant-search.scss
=> fix(date-picker): input date issue

demos/components/select/index.html, src/components/dropdown/dropdown-multiselect/DropdownMultiselectCtrl.js, src/components/dropdown/dropdown-multiselect/dropdown-multiselect.tpl.html, src/components/dropdown/dropdown-multiselect/index.js
=> fix(dropdown):search field configuration issue

src/components/calendar/CalendarCtrl.js
=> fix(date-picker): time set issue

demos/components/dropdown/index.html, demos/components/menus/app.js, demos/components/menus/menus.html, src/components/menus/MenusCtrl.js, src/components/menus/index.js
=> fix(menu): collapse and expandMenus

.travis.yml, demos/components/select/index.html, src/components/dropdown/dropdown-select/DropdownSelectCtrl.js, src/components/dropdown/dropdown-select/__tests__/test-cc-dropdown-select.js, src/components/dropdown/dropdown-select/index.js
=> feat(components/dropdown): 下拉单选 点击选择数据之前增加校验

src/components/dropdown/dropdown-multiselect/DropdownMultiselectCtrl.js
=> fix(dropdown-multi-select): user not choose item and click enter key issue

src/components/calendar/CalendarCtrl.js
=> fix(date-picker): when user not input any value, set time invalid

src/components/dropdown/dropdown-multiselect/DropdownMultiselectCtrl.js
=> fix(dropdown): when user input same search text, can not filter items

demos/components/grid/index.js, src/components/grid/GridCtrl.js
=> fix(grid):数据刷新完成后,再重置scrollbar位置

src/components/calendar/CalendarCtrl.js, src/components/calendar/calendar.tpl.html
=> fix(calendar):switch month button issue

demos/components/modal/modal-header.tpl.html, src/components/draggable/index.js, src/components/modal/ModalService.js, src/components/modal/_modal.scss, src/components/modal/index.js, src/components/modal/modal.tpl.html
=> fix(modal): modal support move function

src/components/date-picker/DatePickerCtrl.js, src/components/dropdown/dropdown-multiselect/DropdownMultiselectCtrl.js, src/components/dropdown/dropdown-multiselect/__tests__/test-cc-dropdown-multiselect.js, src/components/dropdown/dropdown-select/DropdownSelectCtrl.js, src/components/dropdown/dropdown-select/__tests__/test-cc-dropdown-select.js
=> fix(data-picker): scrollbar issue

src/components/sms-preview/SMSPreview.js
=> fix(sms):通道4, 5字数统计问题

demos/components/date-picker/index.html, src/components/date-picker/DatePicker.js, src/components/date-picker/DatePickerCtrl.js, src/components/date-range/date-range.tpl.html
=> fix(date-picker&date-range):add disableScrollIntoView option

demos/components/sms-editor/index.js, src/components/sms-editor/SMSEditorCtrl.js, src/components/sms-preview/SMSPreview.js
=> fix(sms):sms image issue

demos/components/sms-editor/index.js, package-lock.json, package.json, src/components/sms-editor/SMSEditorCtrl.js, src/components/sms-preview/SMSPreview.js
=> fix(sms): special keywords issue

demos/components/sms-editor/index.html, demos/components/sms-editor/index.js, src/components/sms-preview/SMSPreview.js
=> fix(sms):sms tips

demos/components/shop-selector/index.js, mock/mock-shop-selector-grid.js, src/components/shop-selector/ShopSelectorCtrl.js
=> fix(shop-selector): 表格的 resource 请求缺少 serverName 参数

src/components/sms-preview/SMSPreview.js
=> fix(sms): fix sms new line keywords

demos/components/modal/index.html, demos/components/modal/index.js, demos/components/modal/modal-body-child-child.tpl.html, demos/components/modal/modal-body-child.tpl.html, demos/components/modal/modal-body-parent.tpl.html, src/components/modal/ModalService.js
=> fix(modal): fix 双层modal 子modal最大化后导致父modal最大化

src/components/calendar/CalendarCtrl.js, src/components/calendar/calendar.tpl.html
=> fix(date-range):start and end time init value

demos/components/date-picker/index.html, src/components/calendar/Calendar.js, src/components/calendar/CalendarCtrl.js, src/components/date-picker/DatePicker.js, src/components/date-picker/date-picker.tpl.html
=> fix(calendar):add default show value

demos/components/shop-selector/index.js, src/components/shop-selector/ShopSelectorCtrl.js, src/components/shop-selector/ShopSelectorService.js, src/components/shop-selector/service.js
=> fix (shop-selector): 地区接口可配置 

src/components/shop-selector/ShopSelectorCtrl.js
=> fix(shop-selector): 当用户不传入已选店铺时，全部全选按钮失效

src/components/shop-selector/ShopSelectorService.js, src/components/shop-selector/_shop-selector.scss, src/components/shop-selector/shop-selector.tpl.html
=> fix(shop-selector): 调整 loading 样式；表单置灰处理

demos/components/select/index.html, src/components/dropdown/dropdown-multiselect/DropdownMultiselectCtrl.js, src/components/dropdown/dropdown-multiselect/dropdown-multiselect.tpl.html, src/components/dropdown/dropdown-multiselect/index.js, src/components/dropdown/dropdown-select/DropdownSelectCtrl.js
=> fix(dropdown-multiselect): 多选下拉组件添加点击回调函数

src/components/shop-selector/ShopSelectorCtrl.js
=> fix(shop-selector): 当用户传入一个平台为线下时，店铺类型不显示

demos/components/sms-editor/index.js, src/components/sms-preview/SMSPreview.js, src/components/sms-preview/index.js, src/components/sms-preview/sms-preview.tpl.html
=> fix(sms-preview): 将计费规则 tooltip 形式改成文字形式，修改文案

demos/components/goods-selector/index.js, src/components/goods-selector/GoodsSelectorController.js, src/components/goods-selector/constant.js, src/components/goods-selector/goods-seletor-body.tpl.html, src/components/goods-selector/tpls/form-template.tpl.html
=> feat(goods-selector): 删除品牌筛选项(洽课平台)

src/components/tree/node/TreeNodeController.js
=> fix(tree): 搜索功能错误提示修复

demos/components/date-picker/index.html, src/components/calendar/Calendar.js, src/components/calendar/CalendarCtrl.js, src/components/date-picker/DatePicker.js, src/components/date-picker/DatePickerCtrl.js, src/components/date-picker/_date-picker.scss, src/components/date-picker/date-picker.tpl.html, src/components/date-range/date-range.tpl.html
- 调整时间选择器选择时间为空的样式(Windows 火狐上面显示问题) 
- 时间选择器可配置年份显示范围
=> fix(calendar): 支持可配置年份显示范围

demos/components/select/index.html, src/components/dropdown/dropdown-multiselect/DropdownMultiselectCtrl.js
http://jira.yunat.com/browse/CROWD-488
=> fix(dropdownSelect) [多选下拉] 打开下拉，全部全选，点击取消按钮，再次打开下拉，全部全选 checkbox 状态错误

demos/components/select/index.html, package-lock.json, package.json, src/components/dropdown/dropdown-multiselect/DropdownMultiselectCtrl.js
=> 日历组件添加年份限制

demos/components/date-picker/index.html, src/components/calendar/CalendarCtrl.js, src/components/date-picker/DatePickerCtrl.js
http://jira.yunat.com/browse/YYCCMSZXWT-45810
=> :art: [时间选择器]  可自由配置年份范围值
